<a href="https://colab.research.google.com/github/qasim-mansoor/pyTorch/blob/main/Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Fundamentals

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


## Tensors

In [ ]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
# Vector

vector = torch.tensor([7,11])
vector

tensor([ 7, 11])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# Matrix

MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
# Tensor

TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random Tensors

Needed to have a random starting point for the neural network parameters.



In [ ]:
# Create a random tensor of size (3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.4549, 0.4016, 0.1211, 0.3863],
        [0.7659, 0.5503, 0.7617, 0.9849],
        [0.2324, 0.4066, 0.7495, 0.0060]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_tensor.shape

torch.Size([3, 4])

In [ ]:
# Create a random tensor with a similar shape to an image
random_image_tensor = torch.rand(size=(3,224,224)) # height, width, channels(RGB)
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and Ones

In [ ]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

### Creating a range of tensors and tensor-like

In [ ]:
one_to_ten = torch.arange(start=1,end=11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Creating tensors like

ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

**NOTE:** Datatypes important in deep learning

In [ ]:
float_32_tensor = torch.tensor([3.0,6.0,9.0], dtype=None, device=None, requires_grad=False)
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [ ]:
(float_16_tensor * float_32_tensor).dtype

torch.float32

In [ ]:
int_32_tensor = float_32_tensor.type(torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
int_32_tensor * float_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors

In [ ]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.0548, 0.4987, 0.6027, 0.5934],
        [0.3224, 0.7427, 0.2825, 0.3542],
        [0.3561, 0.7303, 0.7859, 0.4700]])

In [ ]:
print(some_tensor)
print(f"Datatype of the tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device the tensor is on: {some_tensor.device}")

tensor([[0.0548, 0.4987, 0.6027, 0.5934],
        [0.3224, 0.7427, 0.2825, 0.3542],
        [0.3561, 0.7303, 0.7859, 0.4700]])
Datatype of the tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device the tensor is on: cpu


### GPU tensor

In [ ]:
# gpu_tensor = torch.rand(3,4, device="cuda")

### Manipulating Tensors (tensor operations)
## Includes:
1. Addition
2. Subtraction
3. Multiplication (Element-wise)
4. Division
5. Matrix multiplication

In [ ]:
# Addition

tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Multiplication

tensor * 10

tensor([10, 20, 30])

In [ ]:
# Subtraction

tensor - 10

tensor([-9, -8, -7])

In [ ]:
# In built functions

torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [ ]:
# Matrix Multiplication

tensor2 = torch.rand(3)
tensor2

tensor([0.8426, 0.8005, 0.8456])

In [ ]:
tensor * tensor

tensor([1, 4, 9])

In [ ]:
torch.matmul(tensor, tensor)

tensor(14)

### Transposing

In [ ]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_A

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [ ]:
tensor_B = torch.tensor([[7,8],
                         [9,10],
                         [11,12]])
tensor_B

tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]])

In [ ]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

### Tensor Aggregation Methods

In [ ]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Min

x.min(), torch.min(x)

(tensor(0), tensor(0))

In [ ]:
# Max

x.max(), torch.max(x)

(tensor(90), tensor(90))

In [ ]:
# Mean - Requries float or complex dtype

x.type(torch.float32).mean(), torch.mean(x.type(torch.float32))

(tensor(45.), tensor(45.))

In [ ]:
# Sum

x.sum(), torch.sum(x)

(tensor(450), tensor(450))

In [ ]:
# Argmin

x.argmin(), torch.argmin(x)

(tensor(0), tensor(0))

In [ ]:
# Argmax

x.argmax(), torch.argmax(x)

(tensor(9), tensor(9))

In [ ]:
# Reshaping, Stacking, Squeezing and Unsqueezing tensors

x = torch.arange(1.,10)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Reshaping

x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
x_reshaped = x.reshape(3,3)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [ ]:
# Changing the View - Only shows a view of a tensor as a different shape, doesnt create a new tensor in memory
z = x.view(3,3)
z

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [ ]:
z[:, 0] = 5
z, x

(tensor([[5., 2., 3.],
         [5., 5., 6.],
         [5., 8., 9.]]),
 tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.]))

In [ ]:
# Stack tensors on top of each other

torch.stack([x,x,x], dim=0)
torch.stack([x,x,x], dim=1)


tensor([[5., 5., 5.],
        [2., 2., 2.],
        [3., 3., 3.],
        [5., 5., 5.],
        [5., 5., 5.],
        [6., 6., 6.],
        [5., 5., 5.],
        [8., 8., 8.],
        [9., 9., 9.]])

In [ ]:
torch.vstack([x,x,x])

tensor([[5., 2., 3., 5., 5., 6., 5., 8., 9.],
        [5., 2., 3., 5., 5., 6., 5., 8., 9.],
        [5., 2., 3., 5., 5., 6., 5., 8., 9.]])

In [ ]:
torch.hstack([x,x,x])

tensor([5., 2., 3., 5., 5., 6., 5., 8., 9., 5., 2., 3., 5., 5., 6., 5., 8., 9.,
        5., 2., 3., 5., 5., 6., 5., 8., 9.])

In [ ]:
# Squeezing
x[0] = 1
print(x)
torch.squeeze(x)

tensor([1., 2., 3., 5., 5., 6., 5., 8., 9.])


tensor([1., 2., 3., 5., 5., 6., 5., 8., 9.])

In [ ]:
y = torch.rand(1,2,1)
print(y)
y_squeezed = y.squeeze()
y_squeezed

tensor([[[0.1761],
         [0.6721]]])


tensor([0.1761, 0.6721])

In [ ]:
# Unsqueezing

print(y_squeezed)
y_unsqueezed0 = y_squeezed.unsqueeze(dim=0)
y_unsqueezed1 = y_squeezed.unsqueeze(dim=1)
y_unsqueezed0, y_unsqueezed1

tensor([0.1761, 0.6721])


(tensor([[0.1761, 0.6721]]),
 tensor([[0.1761],
         [0.6721]]))

In [ ]:
# Permute - Changes order of dimensions - Used mostly with images

x_original = torch.rand(244,244,3) #[height, widht, colour_channel]
x_original

# Rearranging the order of the dimensions

x_permuted = x_original.permute(2,0,1)
x_permuted.shape

print(f"Original: {x_original.shape}")
print(f"Permuted: {x_permuted.shape}")

Original: torch.Size([244, 244, 3])
Permuted: torch.Size([3, 244, 244])


### Indexing - Similar to NumPy



In [ ]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0,0]

tensor([1, 2, 3])

In [ ]:
x[0,0,0]

tensor(1)

In [ ]:
x[0,2,2]

tensor(9)

In [ ]:
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
x[:,1,1]

tensor([5])

In [ ]:
x[:,0,:]

tensor([[1, 2, 3]])

In [ ]:
x[:,:,2]

tensor([[3, 6, 9]])

## Pytorch tensors and NumPy
### Conversion from tensor to ndarray and reverse

In [ ]:
# Numpy array to tensor

import torch
import numpy as np

x = np.arange(0.0,10.0)
torch.from_numpy(x).type(torch.float32)

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
## Tensor to numpy array

tensor = torch.ones(7)
array = tensor.numpy()

tensor, array

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

*Note:* Default dtype of numpy is float64 while default type of torch is float32

## Reproducibility - Seeds

In [ ]:
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_A = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED) # - Everytime random is used, we need to provide a seed for it.
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])


## Accessing GPUs from Pytorch

In [1]:
import torch
torch.cuda.is_available()

True

In [2]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [3]:
torch.cuda.device_count()

1

In [5]:
## Putting tensors (and models) on GPU

tensor = torch.tensor([1,2,3])

print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [7]:
## Moving tensor to GPU (if available)

tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [10]:
## Moving tensor back to CPU
tensor_on_cpu = tensor_on_gpu.to("cpu")
tensor_on_cpu, tensor_on_cpu.device

(tensor([1, 2, 3]), device(type='cpu'))

In [12]:
# Cant convert tensor on GPU to a numpy ndarray. Have to first take it to the CPU

tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [13]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')